name: 'CI Pipeline'
on:
  pull_request:
    branches-ignore:
      - dependabot/**
jobs:
  closed:
    if: github.event.action == 'closed' || github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ryanbas21/update-cors-am-github-action:main
    steps:
      - name: Get deployment URL
        id: deployment
        uses: dorshinar/get-deployment-url@master
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.deployment.outputs.deployment }}
      - name: 'Update CORS in AM'
        uses: ryanbas21/update-cors-am-github-action@latest
        with:
          AM_URL: ${{ secrets.AM_URL }}
          USERNAME: ${{ secrets.AM_USERNAME }}
          PASSWORD: ${{ secrets.AM_PASSWORD }}
          REALM_PATH: ${{ secrets.AM_REALM }}
          ORIGINS: ${{ steps.deployment.outputs.deployment }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
          REDIRECTION_URIS: ${{ secrets.REDIRECTION_URIS }}
          REMOVE: false
          CORS_CONFIG_NAME: ${{ secrets.CORS_CONFIG_NAME }}
  pr:
    strategy:
      matrix:
        node: [16.x] # tests both npm 7 & 8
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node ${{ matrix.node }} Run
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: npm install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
      - run: npx playwright install  --with-deps
      - name: E2E
        run: npm run test:e2e
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # https://www.chromatic.com/docs/github-actions#ui-test-and-ui-review
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing
