name: 'CI Pipeline'
on:
  pull_request:
    branches-ignore:
      - dependabot/**
jobs:
  pr:
    strategy:
      matrix:
        node: [16.x, 18.x]
        os: [macos-latest, ubuntu-latest] #, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node ${{ matrix.node }} Run
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Publish with Verdaccio
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: verdaccio/github-actions/publish@master
      - name: Publish to Chromatic
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node < 17 && !github.event.pull_request.draft }}
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
