name: 'CI Pipeline'
on:
  pull_request:
    branches-ignore:
      - dependabot/**

jobs:
  pr:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node: [16.x] # tests both npm 7 & 8
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node ${{ matrix.node }} Run
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - run: npx playwright install  --with-deps

      - name: E2E
        run: npm run test:e2e
      - name: Publish to Chromatic
        if: ${{ matrix.os }} == 'ubuntu-latest'
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: 'storybook-static'
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing
