# file: .github/workflows/preview.yaml
on:
  pull_request:
    branches:
      - main
      - next
      - beta
      - alpha
jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview
    container:
      image: ghcr.io/ryanbas21/update-cors-am-github-action:main
    outputs:
      urls: ${{ steps.preview_urls.outputs.preview_urls }}
    steps:
      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Deploy preview environment
        uses: okteto/deploy-preview@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: pr-${{ github.event.number }}-ryanbas21
          timeout: 15m
      - name: Get Preview Endpoints
        id: preview_urls
        run: |
          URLS=$(okteto preview endpoints pr-${{ github.event.number }}-ryanbas21 -o json | jq -c)
          echo "::set-output name=preview_urls::$URLS"
  additional:
    needs: preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: ryanbas21/update-cors-am-github-action@latest
        with:
          AM_URL: ${{ secrets.AM_URL }}
          USERNAME: ${{ secrets.AM_USERNAME }}
          PASSWORD: ${{ secrets.AM_PASSWORD }}
          REALM_PATH: ${{ secrets.AM_REALM }}
          ORIGINS: ${{ needs.preview.outputs.urls }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
          REDIRECTION_URIS: ${{ secrets.REDIRECTION_URIS }}
          REMOVE: false
          CORS_CONFIG_NAME: 'org-ui'
      - name: Audit URLs using Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v7
        with: # hope this works because this is an array
          uploadArtifacts: true
          temporaryPublicStorage: true
          urls: |
            https://preview-pr-${{ github.event.number }}-ryanbas21.cloud.okteto.net/
      - name: Lighthouse Report
        uses: manrueda/lighthouse-report-action@v1.1.2
        with:
          reports: '.lighthouseci'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
      - name: Format lighthouse result
        id: lighthouse_result
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: "const links = ${{ steps.lighthouse_audit.outputs.links }}\nconst results = (${{ steps.lighthouse_audit.outputs.manifest }}).filter(result => result.isRepresentativeRun);\nconst score = res => res >= 90 ? '\U0001F7E2' : res >= 50 ? '\U0001F7E0' : '\U0001F534';\nconst comment = results.map((result) => {\n  const summary = result.summary;\n  const url = result.url;\n  return `\n  \U0001F30E [${url}](${url})\n  ⚡️ [Lighthouse report](${links[url]})\n  | Category | Score |\n  | --- | --- |\n  ${Object.keys(summary).map((key) => {\n    const percentage = Math.round(summary[key] * 100);\n    return `| ${score(percentage)} ${key} | ${percentage} |`;\n  }).join('\\n')}\n  `;\n}).join('---');\ncore.setOutput(\"comment\", comment);\n"
      - name: Add Lighthouse comment to PR
        id: lighthouse_comment_to_pr
        if: ${{ always() }}
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          header: lighthouse
          message: |
            ${{ steps.lighthouse_result.outputs.comment }}
  e2e:
    needs: additional
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: install dependencies
        run: npm ci
      - name: install playwright browsers
        run: npx playwright install --with-deps
      - name: E2E
        run: npm run ci:e2e
        env:
          DEBUG: pw:api
          PLAYWRIGHT_TEST_BASE_URL: 'https://preview-pr-${{ github.event.number }}-ryanbas21.cloud.okteto.net'
