name: Release
on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha
      - '*.x'
permissions:
  id-token: write # Enable OIDC
  contents: write
  issues: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.x']
        os: ['ubuntu-latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Set git config username and email
        run: git config user.email "ryan.basmajian@forgerock.com" && git config user.name "ryanbas21"
      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:release
        env:
          NODE_ENV: production
          VITE_FR_AM_URL: ${{ secrets.VITE_FR_AM_URL }}
          VITE_FR_AM_COOKIE_NAME: ${{ secrets.VITE_FR_AM_COOKIE_NAME }}
          VITE_FR_OAUTH_PUBLIC_CLIENT: ${{ secrets.VITE_FR_OAUTH_PUBLIC_CLIENT }}
          VITE_FR_REALM_PATH: ${{ secrets.VITE_FR_REALM_PATH }}
      - name: Release
        run: npx semantic-release
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VITE_FR_AM_URL: ${{ secrets.VITE_FR_AM_URL }}
          VITE_FR_AM_COOKIE_NAME: ${{ secrets.VITE_FR_AM_COOKIE_NAME }}
          VITE_FR_OAUTH_PUBLIC_CLIENT: ${{ secrets.VITE_FR_OAUTH_PUBLIC_CLIENT }}
          VITE_FR_REALM_PATH: ${{ secrets.VITE_FR_REALM_PATH }}
